version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  slack: circleci/slack@3.4.2
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: "Git restore cache"
          keys:
            - source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - source-v{{ .Environment.CACHE_VERSION }}-
      - run:
          name: "Fetch git tags"
          command: |
            mkdir -p ~/.ssh
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            #if [ -e /home/circleci/project/.git ]
            #then
            #  git fetch origin --tags
            #fi
      - checkout
      - run:
          name: "Compress git objects"
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  npm_install_from_cache:
    description: "npm install and save cache"
    steps:
      - run:
          name: "Create cache key"
          command: echo $(find . ./packages/ -maxdepth 2 -name package-lock.json -type f -exec md5sum {} \; | sort -n | md5sum | cut -d" " -f1) >> CACHE_KEY1
      - restore_cache:
          keys:
            - node-v{{ .Environment.CACHE_VERSION }}-{{ checksum "CACHE_KEY1" }}
      - run:
          name: "Install npm packages"
          command: |
            npm run bootstrap
            # if [ -d "./node_modules" ]; then
            #   echo "Found cache. Using cached node_modules."
            #   node_modules/lerna/cli.js link
            # else
            #   echo "Could not find cache. Bootstrapping..."
            #   npm run bootstrap
            # fi
      - save_cache:
          name: "Saving node_modules cache"
          key: node-v{{ .Environment.CACHE_VERSION }}-{{ checksum "CACHE_KEY1" }}
          paths:
            # VERIFY_CACHE_FOLDERS_START (DO NOT REMOVE)
            - "node_modules"
            - "packages/account/node_modules"
            - "packages/bot-skeleton/node_modules"
            - "packages/bot-web-ui/node_modules"
            - "packages/cashier/node_modules"
            - "packages/components/node_modules"
            - "packages/core/node_modules"
            - "packages/dashboard/node_modules"
            - "packages/indicators/node_modules"
            - "packages/p2p/node_modules"
            - "packages/shared/node_modules"
            - "packages/trader/node_modules"
            - "packages/translations/node_modules"
            # VERIFY_CACHE_FOLDERS_END (DO NOT REMOVE)

  build:
    description: "Build"
    steps:
      - run:
          name: "Build all packages"
          command: npm run build

  build_dashboard:
    description: "Build dashboard"
    steps:
      - run:
          name: "Build all packages for deriv dashboard"
          command: npm run build:dashboard

  build_storybook:
    description: "Build storybook"
    steps:
      - run:
          name: "Build all packages for deriv storybook"
          command: npm run build:storybook

  notify_slack:
    description: "Notify slack"
    steps:
      - slack/status:
          include_project_field: false
          failure_message: "Release failed for app.deriv.com with version *$(cat packages/core/dist/version)*"
          success_message: "Release succeeded for app.deriv.com with version *$(cat packages/core/dist/version)*"
          webhook: ${SLACK_WEBHOOK}

  versioning:
    description: "Version the branch"
    parameters:
      target_branch:
        type: string
    steps:
      - attach_workspace:
          at: packages/core/dist
      - run:
          name: Tag
          command: echo "<< parameters.target_branch >>-$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > packages/core/dist/version

  docker_build_push:
    description: "Build and Push image to docker hub"
    parameters:
      docker_image_latest_tag:
        type: string
        default: "latest-staging"
      docker_image_name:
        type: string
        default: "deriv-app"
      docker_file:
        type: string
        default: "Dockerfile"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            #docker build -t ${DOCKHUB_ORGANISATION}/<< parameters.docker_image_name >>:${TAG} -t ${DOCKHUB_ORGANISATION}/<< parameters.docker_image_name >>:<< parameters.docker_image_latest_tag >> - < << parameters.docker_file >>
            docker build -t ${DOCKHUB_ORGANISATION}/<< parameters.docker_image_name >>:${TAG} -t ${DOCKHUB_ORGANISATION}/<< parameters.docker_image_name >>:<< parameters.docker_image_latest_tag >> -f  << parameters.docker_file >> .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/<< parameters.docker_image_name >>

  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_namespace:
        type: string
        default: "deriv-app-staging"
      k8s_service:
        type: string
        default: "deriv-app"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster to namespace << parameters.k8s_namespace >>
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            export NAMESPACE=<< parameters.k8s_namespace >>
            git clone https://github.com/binary-com/devops-ci-scripts
            cd devops-ci-scripts/k8s-build_tools
            echo $CA_CRT | base64 --decode > ca.crt
            ./release.sh << parameters.k8s_service >> ${TAG}
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build

  build_dashboard:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build_dashboard

  release_storybook:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build_storybook
      - versioning:
          target_branch: storybook
      - docker_build_push:
          docker_image_latest_tag: latest
          docker_image_name: "deriv-app-storybook"
          docker_file: "Dockerfile-storybook"
      - k8s_deploy:
          k8s_namespace: "deriv-app-storybook-production"
          k8s_service: "deriv-app-storybook"
      - notify_slack
    environment:
      NODE_ENV: production

  release_staging:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - versioning:
          target_branch: staging
      - docker_build_push
      - k8s_deploy
      - notify_slack
    environment:
      NODE_ENV: staging

  release_staging_dashboard:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build_dashboard
      - versioning:
          target_branch: staging-dashboard
      - docker_build_push:
          docker_image_name: deriv-app-dashboard
          docker_image_latest_tag: latest-staging-dashboard
      - notify_slack
    environment:
      NODE_ENV: staging

  release_production:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - versioning:
          target_branch: production
      - docker_build_push:
          docker_image_latest_tag: latest
      - k8s_deploy:
          k8s_namespace: "deriv-app-production"
      - notify_slack
    environment:
      NODE_ENV: production

  release_production_dashboard:
    docker:
      - image: circleci/node:12.18.0-stretch  
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build_dashboard
      - versioning:
          target_branch: production-dashboard
      - docker_build_push:
          docker_image_name: deriv-app-dashboard
          docker_image_latest_tag: latest
      - notify_slack
    environment:
      NODE_ENV: production
  
  build_and_test:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - run:
          name: "Run tests"
          command: npm test

workflows:
  release_storybook:
    jobs:
      - release_storybook:
          context: binary-frontend-deploy

  release_staging:
    jobs:
      - release_staging
      - release_staging_dashboard

  release_production:
    jobs:
      - release_production:
          context: binary-frontend-deploy

  release_production_dashboard:
    jobs:
      - release_production_dashboard

  test:
    jobs:
      - build_and_test